### ISSUE TITLE
Set jetty user as system user

### ISSUE THREAD

**Issue by jopasserat** [gsick/puppet-jetty#1]
There doesn't seem to be a way to set the jetty user / group created by the module as a system user.

**Comment by gsick** [comment]
Hi,
Now it's a system user, but jetty still needs /bin/bash, it doesn't start properly on centos with /sbin/nologin.
I commited on master if you want to try.

**Comment by jopasserat** [comment]
Almost there :) Could you just make the jetty group a system group as well?
(no problem to force bash for me, my concern was more regarding the UID/GID assigned to jetty)

**Comment by gsick** [comment]
done. You can even force uid/gid if you are using the same across servers
I will make a release when I'd have time.
